"""Initial migration

Revision ID: 675e708a78c0
Revises: 
Create Date: 2020-01-03 22:05:19.343989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '675e708a78c0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('code_repositories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('owner', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notebooks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code_repo_id', sa.Integer(), nullable=True),
    sa.Column('sha', sa.String(), nullable=True),
    sa.Column('path', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('summary', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['code_repo_id'], ['code_repositories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notebooks')
    op.drop_table('code_repositories')
    # ### end Alembic commands ###
